### ISSUE TITLE
"Create reminder" modal is not updated when selecting Channel or Other Users

### ISSUE THREAD

**Issue by c0gnize** [juzser/Rocket.Chat-reminder#10]
Currently unable to create another user or channel reminder.

I am using 1.0.5 version of reminder, installed locally using zip.

It is related with #3 but without any errors in API

**Comment by c0gnize** [comment]
May be helpful. I discovered that after changing `viewId` value to `modal-reminder-create--GENERAL` modal updated correctly

<img width="1306" alt="Screenshot 2023-06-16 at 11 36 15" src="https://github.com/juzser/Rocket.Chat-reminder/assets/12247182/bfc17023-12ac-4e49-b845-1825c564efd3">

**Comment by c0gnize** [comment]
Interesting, when calling `this.read.getMessageReader().getById(null)` instead of undefined it returns non-empty value. I think this is the root of problem

**Comment by juzser** [comment]
Thank you. 
Let me merge this.

**Comment by juzser** [comment]
Release via [v1.0.6](https://github.com/juzser/Rocket.Chat-reminder/releases/tag/v1.0.6)
