### ISSUE TITLE
Remind Team

### ISSUE THREAD

**Issue by lucasplcorrea** [juzser/Rocket.Chat-reminder#15]
There could be an option to send a message in a team, currently it is only available to remind yourself, a public channel, or another person. We could try a function that sends a reminder to a team in which the bot is inserted, what do you think?
/

**Comment by juzser** [comment]
@lucasplcorrea That's a nice idea, let me think the solution, not sure if it's possible.

**Comment by lucasplcorrea** [comment]
I did some research this afternoon, but I don't really understand the Rocket Chat documentation, but I saw in your project documentation that it imports the channels and users from a Rocket Chat source, there must be somewhere that lists the teams, because hubot sees users when they are part of a team, maybe it's something along those lines, I still don't understand much about javascript programs, even less about type script, but I'll try to ask gpt for some help to see if I can get something

**Comment by juzser** [comment]
No worry, I think I know what should do, but I'm not sure because maybe team room data is different with normal room and the permissions too.

**Comment by lucasplcorrea** [comment]
Excellent, if there is anything I can help you with, you can ask me here

**Comment by juzser** [comment]
@lucasplcorrea Sorry for the late reply, but I see it's currently working well with the team. 
I think you just have to recheck the permission of the bot, to allow it post in private channels.
