### ISSUE TITLE
Timezone seems not to be respected

### ISSUE THREAD

**Issue by anicoa** [juzser/Rocket.Chat-reminder#18]
Hello 

first of all thank you very much for the great plugin and all the work.

We found a problem regarding the time of a new created reminder. For us (living in Germany) it's not possible to create a reminder within the next hour, with the message

```
Cannot remind at past
```

I checked the server timezone, it's correct. I did not find any possibility to change timezone of a user, but all time shown in rocketchat is correct. 

Any ideads how we can fix this?

Thanks a lot
Nico

**Comment by juzser** [comment]
@anicoa Which timezone is your server on? Currently I calculate all the time based on timestamp, so I guess it should be correct. 
Btw, I will double check.

**Comment by juzser** [comment]
@anicoa Could you try the new version [v1.0.9](https://github.com/juzser/Rocket.Chat-reminder/releases/tag/v1.0.9) to see if the issue's still occur?
