### ISSUE TITLE
the timezone is not handled correctly

### ISSUE THREAD

**Issue by royburns** [juzser/Rocket.Chat-reminder#2]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/652375/223052208-e7e49f98-029c-4c52-b9a7-4bb6f63d5226.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/652375/223052303-a356d107-7c95-47f2-b40d-52da03860b9e.png">

**Comment by juzser** [comment]
@royburns You should give me more information instead of sending these screenshots only.
