### ISSUE TITLE
unable to create a other user or channel reminder

### ISSUE THREAD

**Issue by alokraj68** [juzser/Rocket.Chat-reminder#3]
Hi,
We are unable to create a other user or channel reminder.
It is giving errors in api call but the list to select channel or otehr users are not popping up anywhere in the modal.

Can you please fix it or can we create a pr for the same?

**Comment by shibiriba** [comment]
Same proplem here

**Comment by juzser** [comment]
@alokraj68 @shibiriba 
Have you set your Default channel in settings? After set the default channel, you have to disable / re-enable the app to take the effect. 
I'm checking from my side but don't see this issue, do you have any log or screenshot of API calling issue? That will be useful to fix.

**Comment by juzser** [comment]
@shibiriba Cool, ok I'm going to update the README soon. 
Sure, if you can create Pull Request or send me the content of PT-BR, then I can update.

**Comment by shibiriba** [comment]
> @shibiriba Cool, ok I'm going to update the README soon. Sure, if you can create Pull Request or send me the content of PT-BR, then I can update.

Of course, I'll look for the files to be translated in the source, but if you can tell me which file the lines to be translated are in, I can speed up the process and maybe deliver it to you next week

**Comment by shibiriba** [comment]
I located the folders according to the readme, I'll start the translation and let you know when it's ready.

**Comment by juzser** [comment]
@shibiriba Are you install the app via RC marketplace or by using command (private app) ?

**Comment by juzser** [comment]
v1.0.4
Status: Reviewing by Rocket.Chat - release soon.
Private app package (github): Ready - [Link](https://github.com/juzser/Rocket.Chat-reminder/releases/tag/v1.0.4)

- Added instruction to README. 
- Added settings to select language. 
- Added pt-br language.
