### ISSUE TITLE
Ver. 1.0.4 doesn' install

### ISSUE THREAD

**Issue by shibiriba** [juzser/Rocket.Chat-reminder#8]
I try to install the new version, with the translations, but isnt intalling or generating a log, try to disable and update, try to remove and install manually, but neither working.
![error](https://user-images.githubusercontent.com/25782509/235167903-850b1967-7d3b-400e-b72d-4b4eb3986a9a.png)

**Comment by juzser** [comment]
I've re-uploaded the v1.0.4 into the release [1.0.4](https://github.com/juzser/Rocket.Chat-reminder/releases/tag/v1.0.4) . You can download and manually update it again.

**Comment by shibiriba** [comment]
I removed the version available in the rocketchat repository, and installed it manually, it worked perfectly, the language selector appears, but some things didn't get the translation, I'll test all the functions and let you know later, I'll open a new call for that too, to not to populate this one that has nothing to do with the subject.
